export const ROUTES = {
  LOGIN: 'Login',
  SIGNUP_FORM: 'SignupForm',
  LOGIN_FORM: 'LoginForm',
  LOGIN_AUTH: 'LoginAuth',
  MAIN: 'Main',
  HOME: 'Home',
  SEARCH: 'Search',
  SEARCH_DETAIL: 'SearchDetail',
  LIBRARY: 'Your Library',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  PLAYLIST: 'Playlist',
  MEDIA_PLAYER: 'MediaPlayer',
  ALL_PLAYLIST: 'AllPlaylist',
  ALL_ARTIST: 'AllArtist',
};